#!/bin/bash                                                                                                                                                                
#SBATCH --mail-type=BEGIN,END,FAIL                                                   
#SBATCH --mail-user=ddhawan@umich.edu                                            
#SBATCH -J N2
#SBATCH -N 1
#SBATCH --ntasks=2
#SBATCH -p batch       
#SBATCH --time=36:00:00       

conda activate runtime
python runtime_calc.py > H2_onsite_ea.txt
